/**
 * Generates the SQL seed for public.role_permissions from shared/auth/permissions.ts,
 * so the database and TypeScript share ONE permission matrix.
 *   npx tsx scripts/db/generate-role-permissions.ts          -> writes the migration
 *   npx tsx scripts/db/generate-role-permissions.ts --check  -> exits 1 if the migration is stale
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { APP_ROLES, ROLE_PERMISSIONS } from '../../shared/auth/permissions.js';

const OUT = 'supabase/migrations/20260926000011_role_permissions_seed.sql';

const rows = APP_ROLES.flatMap((role) => [...new Set(ROLE_PERMISSIONS[role])].sort().map((p) => `  ('${role}', '${p}')`));
const sql = `-- GENERATED by scripts/db/generate-role-permissions.ts from shared/auth/permissions.ts. Do not edit by hand.
-- Re-run the generator after changing the TypeScript matrix; CI checks for drift.
BEGIN;
DELETE FROM public.role_permissions;
INSERT INTO public.role_permissions (role, permission) VALUES
${rows.join(',\n')};
COMMIT;
`;

if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== sql) {
    console.error(`${OUT} is out of date with shared/auth/permissions.ts. Run: npx tsx scripts/db/generate-role-permissions.ts`);
    process.exit(1);
  }
  console.log('role_permissions seed matches shared/auth/permissions.ts');
} else {
  writeFileSync(OUT, sql);
  console.log(`wrote ${OUT} (${rows.length} rows)`);
}
